stages:
    - test

test:
    image: node:latest
    stage: test
    script:
        # install dependencies
        - yarn install --frozen-lockfile
        # start the server in the background
        - yarn dev &
        # run Cypress tests
        - yarn test:e2e
