stages:
    - test-e2e

test-e2e:
    image: node:latest
    stage: test
    script:
        # install dependencies
        - npm ci
        # start the server in the background
        - npm run dev &
        # run Cypress tests
        - npm run e2e
