version: 2.1
orbs:
    cypress: cypress-io/cypress@3
    node: circleci/node@5.1.0
executor:
    docker:
        image: cypress/browsers:node16.16.0-chrome107-ff107-edge

jobs:
  visual-tests:
    executor: node/default
    steps:
      - run:
          name: Upload screenshots to argos-ci.com
          command: npx @argos-ci/cli upload ./screenshots


workflows:
    run all tests:
        jobs:
            - cypress/run:
                  package-manager: "yarn"
                  install-browsers: true
                  start-command: "yarn dev"
                  cypress-command: "yarn test:e2e"
            - visual-tests:
                requires:
                    - cypress/run
