on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:e2e # will run `yarn test` command
      - name: Upload screenshots
        run: npx @argos-ci/cli upload cypress/screenshots
