on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Run install
        run: yarn install --frozen-lockfile 
      - name: Test the app
        run: yarn test:e2e
      - name: Upload screenshots
        run: npx @argos-ci/cli upload cypress/screenshots
